---
output: html_document
editor_options: 
  chunk_output_type: console
---
Exploration of the MARINe dataset, while touching up Erica's code.

Import Libraries

```{r}
### This code is to calculate species diversity indexes for Dangermond Preserve and surrounding areas
### Written by Erica Nielsen, 2024 using MARINe dataset from UCSC

# load libraries
library(dplyr)
library(tidyr)
library(readxl)
library(ggplot2)
library(maps)
library(viridis)
library(here)
```

Import data

```{r}
# first upload data and filter

#read point contact
pt_cont <- read_excel(here::here("data/MARINe_biodiversity_data/cbs_data_CA_2023.xlsx"), 
                      sheet = "point_contact_summary_data")

#read quadrat summary
quad <- read_excel(here::here("data/MARINe_biodiversity_data/cbs_data_CA_2023.xlsx"), 
                   sheet = "quadrat_summary_data")

#read swath data
swath <- read_excel(here::here("data/MARINe_biodiversity_data/cbs_data_CA_2023.xlsx"), 
                    sheet = "swath_summary_data")
```

Clean Data

```{r}
#Here we remove species lumps ("spp"), and all other non-species-level data 
remove_chars = c("Rock", "Sand", "Tar", "Blue Green Algae", "Red Crust", "Diatom", "Ceramiales")
pt_cont_f <- pt_cont[ !grepl(paste(remove_chars, collapse="|"), pt_cont$species_lump),]
#only need to do for pt count and quadrat data
pt_cont_f <- pt_cont %>% 
    filter(!grepl(remove_chars, species_lump))

quad_f <- quad %>% 
    filter(!(species_lump %in% remove_chars))
```

```{r}
# edit tables so we have anything with total_count or number_of_hits > 0 is 1 (i.e. pres/abs)
# also filter to mainland (includes islands too tricky at this time)
pt_cont_P <- pt_cont_f %>%
  filter(island == "Mainland") %>%
  mutate(number_of_hits = ifelse(number_of_hits > 0, 1, number_of_hits)) %>%
  #rename so pres/abs col is called 'total_count' (so we can merge later)
  rename(total_count = number_of_hits)

quad_P <- quad_f %>%
  filter(island == "Mainland") %>%
  mutate(total_count = ifelse(total_count > 0, 1, total_count))

swath_P <- swath %>%
  filter(island == "Mainland") %>%
  mutate(total_count = ifelse(total_count > 0, 1, total_count))
```

```{r}
# now join dataframes to make single pres/abs spp table
common_col_names <- intersect(names(quad_P), names(swath_P)) # get column names
quad_swath_P <- merge(quad_P, swath_P, by=common_col_names, all.x=TRUE, all.y=TRUE) #merge first 2 DFs
common_col_names <- intersect(names(pt_cont_P), names(quad_swath_P)) #get column names
all_pres <- merge(pt_cont_P, quad_swath_P, by=common_col_names, all.x=TRUE, all.y=TRUE) #merge in swath
all_pres_f <- all_pres[,c(1,3,4,14,15,16)] #only include relevant columns
```

